### ISSUE TITLE
"ImportError: DLL load failed" when trying to run built pygiftgrab.pyd on Windows

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/GIFT-Grab#96]
https://gitlab.com/gift-surg/GIFT-Grab/-/jobs/197082075

```
[...]
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x00000263773C12B0>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
[...]
```

I have a suspicion that this is not caused by `pygiftgrab.pyd` itself, but by the `giftgrab.dll` dependencies, which the system fails to resolve, due to not being accessible (i.e. not in the environment's `PATH`). In this case the dependencies of `giftgrab.dll` are (as listed in the main CMake config):

* `${PYTHON_LIBRARIES}`
* `${Boost_LIBRARIES}`
* `${EpiphanSDK_LIBS}`

* [x] also need to find out whether these have dependencies of their own that need to be resolved

The dependencies of `pygiftgrab.pyd` are:

* `${Boost_LIBRARIES}`
* `giftgrab.dll` itself (which is generated in the same folder as `pygiftgrab.pyd`)

One further problem is that the error message does not really say which dependency it's missing, which [could be figured out](https://vxlabs.com/2017/12/06/how-to-debug-pyinstaller-dll-pyd-load-failed-issues-on-windows/) by the [Dependencies](https://github.com/lucasg/Dependencies) tool (which does not sound very easy to install, though).

**Comment by dzhoshkun** [comment]
After appending the runtime paths above to `PATH`, the error is different:

```
[…]
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x00000116832A4320>
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: %1 is not a valid Win32 application.
[…]
```

**Comment by dzhoshkun** [comment]
Resolved by using the path to the **64-bit** Epiphan `frmgrab.dll` instead of the 32-bit one.
